---
- name: Append kitana_keys to authorized_keys for multiple users
  hosts: all
  gather_facts: false

  vars:
    user_names:
      - abryand10
      - abryang6

  tasks:
    - name: Append kitana_keys to authorized_keys
      ansible.builtin.lineinfile:
        path: "~{{ item }}/.ssh/authorized_keys"
        line: "{{ lookup('file', 'kitana_keys') }}"
        create: true
        state: present
      loop: "{{ user_names }}"
